import './globals.css'

export const metadata = {
  title: 'JalanKita',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="poppins bg-slate-200">{children}</body>
    </html>
  )
}
